site_name:     Boii's Wiki
site_url:      https://wiki.boii.xyz
site_author:   Boii
repo_url:      https://github.com/TCP404/WIKI/
repo_name:     GitHub
remote_branch: gh-pages
remote_name:   origin
dev_addr:      127.0.0.1:8000
copyright:     Copyright © 2024 [Mr.Boii](https://www.boii.xyz)

theme:
  name: material # pip install mkdocs-material
  logo: _assets/logo/favicon.png
  favicon: _assets/logo/favicon.png
  font:
    text: Inter
    code: 'Fira Code'
  highlightjs: true
  hljs_languages:
        - yaml
        - rust
  icon:
    admonition:
      note:     fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info:     fontawesome/solid/circle-info
      tip:      fontawesome/solid/bullhorn
      success:  fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning:  fontawesome/solid/triangle-exclamation
      failure:  fontawesome/solid/bomb
      danger:   fontawesome/solid/skull
      bug:      fontawesome/solid/robot
      example:  fontawesome/solid/flask
      quote:    fontawesome/solid/quote-left
  palette: # 明亮/黑暗模式
    - media: "(prefers-color-scheme)" # 跟随系统
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" # 亮色模式
      scheme: primary
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
        primary: blue
    - media: "(prefers-color-scheme: dark)" # 暗色模式
      scheme: slate #
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.tabs         # 横栏导航
    - navigation.tabs.sticky  # 滚动时隐藏顶部nav，需要配合navigation.tabs使用
    - navigation.tracking     # 在url中使用标题定位锚点
    - navigation.indexes      # 指定节点index pages ，跟instant不兼容
    - navigation.top          # 一键回顶部
    - navigation.sections     # nav节点缩进
    - navigation.path         # 显示当前页面的路径（面包屑）

    - content.code.annotate # 代码注释美化，变成一个圆点，鼠标点击显示注释内容。Ref：https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - toc.follow      # 跟随滚动
    # - toc.integrate # 左侧生产目录
    - content.tooltips
    - announce.dismiss
    - header.autohide
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  # 图片支持
  - attr_list
  - md_in_html

  - abbr                  # 名词解释支持，Ref：https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
  - pymdownx.magiclink    # 智能链接支持，Ref：https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  - pymdownx.smartsymbols # 智能符号支持，Ref：https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
  - footnotes             # 脚注支持，   Ref：https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - meta                  # 文章前部的 font-matter 元数据支持

  # 引用块美化，Ref：https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.betterem:  # 智能识别加粗和斜体等符号
      smart_enable: all # [all 全部开| none 全部关| asterisk 仅对星号起作用| underscore 仅对下划线起作用]

  - pymdownx.arithmatex: # 对数据公式的支持
      generic: true

  - toc:
      permalink: true

  # 对上、下标、文本高亮、键盘样式的支持，Ref：https://squidfunk.github.io/mkdocs-material/reference/formatting/#adding-keyboard-keys
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # 对代码高亮的支持，Ref：https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true

  - codehilite:
      guess_lang: false
      linenums: true

  # emoji 支持
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # 列表支持，Ref：https://squidfunk.github.io/mkdocs-material/reference/lists/
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search # necessary for search to work
  # - git-revision-date-localized
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  # - encryptcontent:
  #     title_prefix: ' '
  #     password_file: 'passwords.yml' # file with password inventory
  #     password_button: True
  #     input_class: 'w3-input' # CSS class used for input username and password
  #     button_class: 'w3-button w3-theme-l1 w3-hover-theme' # CSS class for password_button

extra_css:
  - _assets/css/extra.css

extra_javascript:
  - _assets/js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - _assets/js/tablesort.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - _assets/js/umlconvert.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - _assets/js/glightbox.min.js
  - _assets/js/shortcuts.js

nav:
  - "Home": index.md

  - "Golang":
      - Basic:
          - 0.总叙:        Go/Basic/Golang-0-总叙.md
          - 1.基础:        Go/Basic/Golang-1-基础.md
          - 2.数据类型:    Go/Basic/Golang-2-数据类型.md
          - 3.运算符:      Go/Basic/Golang-3-运算符.md
          - 4.流程控制:    Go/Basic/Golang-4-流程控制.md
          - 5.数组:        Go/Basic/Golang-5-数组.md
          - 6.slice:       Go/Basic/Golang-6-slice.md
          - 7.map:         Go/Basic/Golang-7-map.md
          - 8.函数:        Go/Basic/Golang-8-函数.md
          - 9.指针:        Go/Basic/Golang-9-指针.md
          - 10.结构体:     Go/Basic/Golang-10-结构体.md
          - 11.包:         Go/Basic/Golang-11-包.md
          - 12.接口:       Go/Basic/Golang-12-接口.md
          - 13.面向对象:   Go/Basic/Golang-13-面向对象.md
          - 14.错误与异常: Go/Basic/Golang-14-错误与异常.md
          - 15.单元测试:   Go/Basic/Golang-15-单元测试.md
          - 16.泛型:       Go/Basic/Golang-16-泛型.md
          - Other:
              - 类型转换:      Go/Basic/Golang-类型转换.md
              - Go Module:     Go/Basic/Golang-Go-Module.md
              - Go Workspace:  Go/Basic/Golang-Go-Workspace.md
      - Advanced:
          - 并发:     Go/Advanced/Golang-16-并发.md
          - Channel:  Go/Advanced/Golang-17-Channel.md
          - 并发安全: Go/Advanced/Golang-18-并发安全.md
          - 反射:     Go/Advanced/Golang-19-reflect.md
          - GPM:     Go/Advanced/Golang-GPM模型.md
          - 坑:      Go/Advanced/Golang-go并发的坑.md
          - 并发模型: Go/Advanced/Golang-并发模型.md
      - Gin:
          - Get start: Go/Framework/gin/Gin-0-Get-Start.md
          - 返回数据:  Go/Framework/gin/Gin-1-返回数据.md
          - 接收请求:  Go/Framework/gin/Gin-2-接收请求.md
          - 路由组:    Go/Framework/gin/Gin-3-路由组.md
          - 上传下载重定向: Go/Framework/gin/Gin-4-上传下载重定向.md
          - 中间件:    Go/Framework/gin/Gin-5-中间件.md
      - Standard Library:
          - 0-time:    Go/StdLib/0-time-时间与日期.md
          - 1-random:  Go/StdLib/1-random-随机数.md
          - 2-flag:    Go/StdLib/2-flag-命令行解析.md
          - 3-log:     Go/StdLib/3-log-日志服务.md
          - 4-fmt:     Go/StdLib/4-fmt-格式化.md
          - 5-strings: Go/StdLib/5-strings-字符串操作.md
          - 6-json:    Go/StdLib/6-json.md
          - File & IO:
              - IO:    Go/StdLib/File&IO/io.md
              - Bufio: Go/StdLib/File&IO/bufio.md
          # - net:
      - Socket:
          - IM-System:
              - 1-搭建基础服务:      Go/Socket/IM-System/IM1-搭建基础服务.md
              - 2-上线广播功能:      Go/Socket/IM-System/IM2-上线广播功能.md
              - 3-消息群发功能:      Go/Socket/IM-System/IM3-消息群发功能.md
              - 4-业务封装:         Go/Socket/IM-System/IM4-业务封装.md
              - 5-在线用户查询功能:  Go/Socket/IM-System/IM5-在线用户查询功能.md
              - 6-修改用户名功能:    Go/Socket/IM-System/IM6-修改用户名功能.md
              - 7-超时强踢功能:      Go/Socket/IM-System/IM7-超时强踢功能.md
              - 8-私聊功能:         Go/Socket/IM-System/IM8-私聊功能.md
              - 9-客户端框架:       Go/Socket/IM-System/IM9-客户端框架.md
              - 10-命令行解析:      Go/Socket/IM-System/IM10-命令行解析.md
              - 11-发送请求:        Go/Socket/IM-System/IM11-发送请求.md
      - nil:
          - 交叉编译:     Go/nil/Golang-nil-交叉编译.md
          - 选项设计模式:  Go/nil/Golang-nil-选项设计模式.md
          - 1-for&range: Go/nil/Golang-nil-1-for&range.md
          - 2-slice原理: Go/nil/Golang-nil-2-slice.md
          - 3-map原理:   Go/nil/Golang-nil-3-map.md
          - 4-string原理: Go/nil/Golang-nil-4-string.md
          - 5-chan原理:   Go/nil/Golang-nil-5-chan.md
          - 6-struct原理: Go/nil/Golang-nil-6-struct.md
          - 7-关于nil:    Go/nil/Golang-nil-7-关于nil.md
          - 8-值实现&指针实现: Go/nil/Golang-nil-8-值实现与指针实现.md
          - 9-实现抽象类: Go/nil/Golang-nil-9-实现抽象类.md
          - 10-反射: Go/nil/Golang-nil-10-反射.md

  - "Rust":
      - Basic:
          - "0-Hello": Rust/Basic/0-Hello.md
          - "1-变量":  Rust/Basic/1-变量.md
          - "2-数据类型": 
              - "2.1-数据类型": Rust/Basic/2.1-数据类型.md
              - "2.2-字符串": Rust/Basic/2.2-字符串.md
          - "3-函数": Rust/Basic/3-函数.md
          - "4-流程控制": Rust/Basic/4-流程控制.md
          - "5-所有权": Rust/Basic/5-所有权.md
          - "6-结构体": Rust/Basic/6-结构体.md

  - "Python":
      - Basic:
          - 总叙:       Python/Basic/Python-No-1-Abstract.md
          - 基础:       Python/Basic/Python-No-2-Basic.md
          - 判断和循环: Python/Basic/Python-No-3-Judge&Loop.md
          - 数据类型:   Python/Basic/Python-No-4-Data-Type.md
          - 运算符:     Python/Basic/Python-No-5-Operator.md
          - 函数:       Python/Basic/Python-No-6-Function.md
          - 错误处理:   Python/Basic/Python-No-7-Error-Handle.md
          - 调试:       Python/Basic/Python-No-8-Debug.md
          - 测试:       Python/Basic/Python-No-9-Test.md
          - 模块:       Python/Basic/Python-No-10-Module.md
          - File:       Python/Basic/Python-No-19-File.md
          - IO:         Python/Basic/Python-No-20-IO.md
      - Advanced:
          - 高级特性:   Python/Advanced/Python-No-Feature-High-Level-Feature.md
          - 工具类:     Python/Advanced/Python-No-Feature-Utility-Class.md
          - 函数式编程: Python/Advanced/Python-No-Feature-Functional.md
          - 面向对象:
              - 类和对象: Python/Advanced/OOP/Python-No-11-Class&Object.md
              - 私有化:   Python/Advanced/OOP/Python-No-12-Privatization.md
              - 魔术方法: Python/Advanced/OOP/Python-No-13-Magic-Method.md
              - 枚举类:  Python/Advanced/OOP/Python-No-14-Enum.md
          - 进程线程:
              - 总叙: Python/Advanced/Thread/Python-No-15-Abstract.md
              - 进程: Python/Advanced/Thread/Python-No-16-Process.md
              - 线程: Python/Advanced/Thread/Python-No-17-Thread.md
              - 协程: Python/Advanced/Thread/Python-No-18-Coroutine.md
      - Builtin:
          - json: Python/Builtin/Python-No-Builtin-json.md
          - re:   Python/Builtin/Python-No-Builtin-re.md
      - Type:
          - string: Python/Type/Python-No-Type-String.md
      - Crawler:
          - 总叙:     Python/Crawler/Python-Crawler-0-Crawler-Abstract.md
          - 通用爬虫: Python/Crawler/Python-Crawler-1-General-Crawler.md
          - 聚焦爬虫: Python/Crawler/Python-Crawler-2-Focused-Crawler.md

  - "Linux":
    - Basic:
        - 进程:       Linux/Basic/进程.md
        - 文件和链接: Linux/Basic/文件和链接.md
        - 文件系统:   Linux/Basic/文件系统.md
        - Command1:   Linux/Basic/Command1.md
        - Command2:   Linux/Basic/Command2.md
        - 1.md:       Linux/Basic/1.md
    - Shell:
        - 1-基本语法:           Linux/Shell/Shell-1-基本语法.md
        - 2-函数、数组、重定向: Linux/Shell/Shell-2-函数、数组、重定向.md
        - 3-表达式:             Linux/Shell/Shell-3-表达式.md
        - 4-字符串处理:         Linux/Shell/Shell-4-字符串处理.md

  - "Storage":
    - "Redis":
      - Get Start:   Redis/1-Get-Start.md
      - Type:
        - String: Redis/2-1-type-string.md
        - List:   Redis/2-2-type-list.md
        - Set:    Redis/2-3-type-set.md
        - ZSet:   Redis/2-4-type-zset.md
        - Hash:   Redis/2-5-type-hash.md
      - Persistence: Redis/3-persistence.md
      - Transaction: Redis/4-transaction.md

    - "MongoDB":
      - 0-Hello: Mongo/0-Hello.md
      - 1-文档:   Mongo/1-文档.md

    - "MySQL":
      - 0-Hello:  MySQL/0-Hello.md
      - 1-数据类型: MySQL/1-数据类型.md
      - 2-SQL:    MySQL/2-SQL.md
      - 3-索引:   MySQL/3-索引.md
      - 4-explain: MySQL/4-explain.md
      - 5-事务:   MySQL/5-事务.md
      - 6-锁:     MySQL/6-锁.md
      - 7-日志:   MySQL/7-日志.md
      - 存储结构:  MySQL/存储结构.md
      - 执行过程:  MySQL/执行过程.md
    - "ES":
      - 0-Hello: ES/0-Hello.md
      - 1-索引基本操作: ES/1-索引基本操作.md
      - 2-映射基本操作: ES/2-映射基本操作.md
      - 3-文档基本操作: ES/3-文档基本操作.md
      - 4-Query-DSL:  ES/4-Query-DSL.md
      - 5-Script:     ES/5-script.md
      - 6-聚合分析:    ES/6-聚合分析.md

  - "408":
    - 数据结构:
      - 0-绪论:         408/DataStructure/0-绪论.md
      - 1-算法:         408/DataStructure/1-算法.md
      - 2-线性表:       408/DataStructure/2-线性表.md
      - 3-栈:           408/DataStructure/3-栈.md
      - 4-队列:         408/DataStructure/4-队列.md
      - 5-串:           408/DataStructure/5-串.md
      - 6-树:           408/DataStructure/6-树.md
      - 7-图:           408/DataStructure/7-图1.md
      - 8-图的存储结构: 408/DataStructure/8-图2.md
      - 9-图的算法:     408/DataStructure/9-图3.md
    - 网络:
      - HTTP: 408/NET/HTTP.md
      - CSP-Header: 408/NET/CSP-Header.md

  - 分布式:
      - 0-Hello: Distributed/0-Hello.md
      - 1-分布式算法: Distributed/1-分布式算法.md
      # - 1-分布式事务: Distributed/1-分布式事务.md
      # - 2-分布式锁:   Distributed/2-分布式锁.md
      # - 3-分布式缓存: Distributed/3-分布式缓存.md
      # - 4-分布式消息队列: Distributed/4-分布式消息队列.md
      # - 5-分布式搜索引擎: Distributed/5-分布式搜索引擎.md
      # - 6-分布式文件系统: Distributed/6-分布式文件系统.md
      # - 7-分布式存储: Distributed/7-分布式存储.md
      # - 8-分布式计算: Distributed/8-分布式计算.md
      # - 9-分布式调度: Distributed/9-分布式调度.md

  - Other:
      - Example: example.md